# Generated by Django 3.1.7 on 2021-03-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
