# Generated by Django 3.1.7 on 2021-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0005_auto_20210310_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(),
        ),
    ]
