# Generated by Django 3.1.7 on 2021-03-11 09:26

from django.db import migrations, models
import simpleblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0006_auto_20210311_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(help_text='Enter the date of purchase', validators=[simpleblog.models.present_future]),
        ),
    ]
