# Generated by Django 3.1.7 on 2021-03-11 09:51

import datetime
from django.db import migrations, models
import simpleblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0007_auto_20210311_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2021, 3, 11), help_text="If you don't like to publish immediately please enter future post date ", validators=[simpleblog.models.present_future]),
        ),
    ]
